### ISSUE TITLE
Appending all images one after other. Ignores middle div blocks

### ISSUE THREAD

**Issue by anand45** [LukyVj/Colorify.js#24] opened 2015-12-30 18:58 UTC
<b>For following HTML mackup</b>

``` html
<div colorify-main-color class="image-container">
    <img colorify src="images/demo/image.jpg" width="200" height="200">
</div>
<div class="other-dive-in-between">
    Some content in between two images blocks(DIVs)
</div>
<div colorify-main-color class="image-container">
    <img colorify src="images/demo/image.jpg" width="200" height="200">
</div>
```

<b>script </b>

``` javascript
colorify({

  container: 'colorify-main-color',
  attr: 'colorify', 
  images: false,
  accuracy: 100,
  gradient: false,
  gradientDirection: false,
  padding: 4,
  lazyReveal: false,
  give: false,
  revealOn: false
});
```

Its output both the images one by one ignoring div in between these two image blocks and throws out of image main container 

<b>Output result HTML</b>

``` html
<div colorify-main-color="" class="image-container">
    <div class="image-container" style="padding: 4px; background-color: rgb(132, 144, 150);"><img colorify="" src="images/demo/image.jpg" width="200" height="200" colorify-main-color-1="" class="colorify visible all-not-loaded"></div>
    <div class="image-container" style="padding: 4px; background-color: rgb(132, 144, 150);"><img colorify="" src="images/demo/image.jpg" width="200" height="200" colorify-main-color-1="" class="colorify visible all-loaded"></div>
</div>

<div class="other-dive-in-between">
    Some content in between two images blocks(DIVs)
</div>
```

**Comment by LukyVj** [comment] 2015-12-30 19:02
Hello ! 
Thank you for your detailled issue.
I'm looking into it right now, updating you asap.

**Comment by LukyVj** [comment] 2015-12-30 19:11
Update : Bug reproduced, now fixing it.

**Comment by LukyVj** [comment] 2015-12-30 19:20
Okay, so, I found out why it was buggy. 
Since it's the very first version of the script, you have to pay attention and to wrap images in UNIQUES containers. 

So, for example, if you want the colorify.js script to process two images, in the same way, with 2 different containers but the same images settings, you have to make the container's id unique. 

If you use the following code, your problem should be fixed. 

``` html
<div colorify-main-color class="image-container">
    <img colorify src="images/demo/image.jpg" width="200" height="200">
</div>
<div class="other-dive-in-between">
    Some content in between two images blocks(DIVs)
</div>
<div colorify-main-color-2 class="image-container">
    <img colorify-2 src="images/demo/image.jpg" width="200" height="200">
</div>
```

with this JS code : 

``` javascript
colorify({
  container: 'colorify-main-color',
  attr: 'colorify', 
  images: false,
  accuracy: 100,
  gradient: false,
  gradientDirection: false,
  padding: 4,
  lazyReveal: false,
  give: false,
  revealOn: false
});

colorify({
  container: 'colorify-main-color-2',
  attr: 'colorify-2', 
  images: false,
  accuracy: 100,
  gradient: false,
  gradientDirection: false,
  padding: 4,
  lazyReveal: false,
  give: false,
  revealOn: false
});
```

Notice how the containers attributes, and the images attributes are different `colorify-main-color` / `colorify-main-color-2` & `colorify`/ `colorify-2`.

To avoid those problems, I make the `attr` property facultative. If you just give the containers an unique ID, it will be applied to the images in this container.

But I agree on a point, the V1 of colorify could be hugely improved, and that's what I'm actually doing, making it better, based on you guys feedbacks !

**Comment by LukyVj** [comment] 2015-12-30 19:25
Also, you can write the JS this way, which would have the exact same effect : 

``` javascript
colorify({
  container: 'colorify-main-color',
  attr: 'colorify', 
  accuracy: 100,
  padding: 4
});

colorify({
  container: 'colorify-main-color-2',
  attr: 'colorify-2', 
  accuracy: 100,
  padding: 4
});
```

**Comment by anand45** [comment] 2015-12-30 19:28
Thanks LukyVj,

But i need to handle 100 of image sets like this :)  , Is there any provision to add dynamic(say multiple) attr and container with in single  colorify({}) methode. it would be great if you add so in further release.. thanks

**Comment by LukyVj** [comment] 2015-12-30 19:33
``` javascript
colorify({
  container: 'colorify-main-color',
  images: ['image1.png','image2.png','image3.png'], // And so on.. (to 100 )
  attr: 'colorify', 
  accuracy: 100,
  padding: 4
});
```

But I cannot guarantee you it will process all of them, neither the time of the process. 
I'd love to be updated on your project, tell me if you have any other issues.

**Comment by LukyVj** [comment] 2016-01-06 12:53
So, I made a few tests

``` text
 Images process tests :
  No internet connection, chrome47.
  - 200 accuracy, 8sec to display 280 images
  - 200 accuracy, 14sec to display 560 images
```

I would say, the less images you process, faster the processing will be.

**Closed as completed by LukyVj** 2016-01-06 12:53 UTC
Labels: bug, enhancement
